canton {
  sequencers {
    sequencer1 {
      storage {
        type = postgres
        config {
          dataSourceClassName = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "postgres"
            portNumber = 5432
            databaseName = "sequencer"
            user = "canton"
            password = "canton"
          }
        }
      }
      public-api {
        address = "0.0.0.0"
        port = 5001
      }
      admin-api {
        address = "0.0.0.0"
        port = 5002
      }
      sequencer {
        type = reference
        config {
          storage {
            type = postgres
            config {
              dataSourceClassName = "org.postgresql.ds.PGSimpleDataSource"
              properties = {
                serverName = "postgres"
                portNumber = 5432
                databaseName = "sequencer_driver"
                user = "canton"
                password = "canton"
              }
            }
          }
        }
      }
    }
  }

  mediators {
    mediator1 {
      storage {
        type = postgres
        config {
          dataSourceClassName = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "postgres"
            portNumber = 5432
            databaseName = "mediator"
            user = "canton"
            password = "canton"
          }
        }
      }
      admin-api {
        address = "0.0.0.0"
        port = 5202
      }
    }
  }

  participants {
    participant1 {
      storage {
        type = postgres
        config {
          dataSourceClassName = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "postgres"
            portNumber = 5432
            databaseName = "participant1"
            user = "canton"
            password = "canton"
          }
        }
      }
      ledger-api {
        address = "0.0.0.0"
        port = 5011
      }
      admin-api {
        address = "0.0.0.0"
        port = 5012
      }
      http-ledger-api {
        address = "0.0.0.0"
        port = 5013
      }
    }

    participant2 {
      storage {
        type = postgres
        config {
          dataSourceClassName = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "postgres"
            portNumber = 5432
            databaseName = "participant2"
            user = "canton"
            password = "canton"
          }
        }
      }
      ledger-api {
        address = "0.0.0.0"
        port = 5021
      }
      admin-api {
        address = "0.0.0.0"
        port = 5022
      }
      http-ledger-api {
        address = "0.0.0.0"
        port = 5023
      }
    }
  }
}
