/**
 * TypeScript bindings for the Daml smart contracts.
 *
 * The Daml JSON Ledger API v1 represents:
 *   - Daml `Decimal`  → JSON string  (avoids floating-point rounding)
 *   - Daml `Party`    → JSON string  (the full Canton party ID)
 *   - Daml `[Party]`  → JSON array of strings
 *   - Daml `ContractId T` → JSON string (format: "#txHash:eventIndex")
 *   - Daml tuples     → JSON arrays (e.g. `(ContractId A, ContractId B)` → `["#0:1","#0:2"]`)
 */

/** Daml Decimal serialized as a string to preserve precision. */
export type DamlDecimal = string;

// ─── Template payloads ────────────────────────────────────────────────────────

/** Asset template — a tokenized holding. (contracts/daml/Asset.daml) */
export interface Asset {
  issuer: string;
  owner: string;
  symbol: string;
  quantity: DamlDecimal;
  observers: string[];
}

/** SwapProposal template — a pending offer from proposer to counterparty. */
export interface SwapProposal {
  proposer: string;
  counterparty: string;
  settler: string;
  offeredAssetCid: string;
  offeredSymbol: string;
  offeredQuantity: DamlDecimal;
  requestedSymbol: string;
  requestedQuantity: DamlDecimal;
}

/** SwapSettlement template — an accepted swap awaiting atomic execution. */
export interface SwapSettlement {
  proposer: string;
  counterparty: string;
  settler: string;
  offeredAssetCid: string;
  counterpartyAssetCid: string;
  offeredSymbol: string;
  offeredQuantity: DamlDecimal;
  requestedSymbol: string;
  requestedQuantity: DamlDecimal;
}

/** TransferRequest — owner pre-authorizes operator to transfer their asset. */
export interface TransferRequest {
  operator: string;
  owner: string;
  newOwner: string;
  assetCid: string;
}

/** TransferBatch — operator groups N TransferRequests for 1-roundtrip execution. */
export interface TransferBatch {
  operator: string;
  requests: string[];
}

// ─── JSON API envelope types ──────────────────────────────────────────────────

/** A contract returned by the JSON API query or create endpoints. */
export interface Contract<T> {
  contractId: string;
  payload: T;
  templateId: string;
}

/** Result of exercising a choice via the JSON API. */
export interface ExerciseResult<R> {
  /** The return value of the Daml choice. */
  exerciseResult: R;
  /** All ledger events generated by this transaction (created / archived). */
  events: LedgerEvent[];
}

export type LedgerEvent =
  | { created: Contract<unknown> }
  | { archived: { contractId: string; templateId: string } };

/** Party descriptor returned by GET /v1/parties. */
export interface PartyInfo {
  identifier: string;
  displayName: string;
  isLocal: boolean;
}

// ─── Utility types ────────────────────────────────────────────────────────────

/**
 * Type for Daml choices that take no arguments (i.e. `choice Foo : () controller ...`).
 * Daml's unit `()` maps to an empty JSON object `{}`.
 */
export type EmptyArg = Record<string, never>;

/**
 * Convert a JavaScript number to a Daml-compatible Decimal string.
 * Avoids the verbosity of `.toFixed(N)` while preserving exactness.
 * Daml accepts "100", "100.5", "33.333333" — all valid Decimal representations.
 */
export function toDecimalString(n: number): string {
  return String(n);
}

// ─── Template ID constants ────────────────────────────────────────────────────
/**
 * Template IDs in the Canton JSON Ledger API v2 format:
 *   "#<packageName>:<ModuleName>:<EntityName>"
 *
 * The "#" prefix means "resolve by package name" (from the package's daml.yaml).
 * Package name: "asset-swap-contracts" (defined in daml-contracts/contracts/daml.yaml).
 *
 * This format is stable across DAR uploads with the same package name, which
 * enables the smart contract upgrading feature in Canton.
 */
export const TEMPLATE_IDS = {
  ASSET:            '#asset-swap-contracts:Asset:Asset',
  SWAP_PROPOSAL:    '#asset-swap-contracts:SwapProposal:SwapProposal',
  SWAP_SETTLEMENT:  '#asset-swap-contracts:SwapProposal:SwapSettlement',
  TRANSFER_REQUEST: '#asset-swap-contracts:TransferBatch:TransferRequest',
  TRANSFER_BATCH:   '#asset-swap-contracts:TransferBatch:TransferBatch',
} as const;
